In [1]:
# Test TA-LIB
import numpy
import talib

close = numpy.random.random(100)

In [2]:
output = talib.SMA(close)

In [3]:
from talib import MA_Type

upper, middle, lower = talib.BBANDS(close, matype=MA_Type.T3)

In [4]:
output = talib.MOM(close, timeperiod=5)
output

array([        nan,         nan,         nan,         nan,         nan,
       -0.51489137,  0.15208411, -0.38260074, -0.62264083,  0.90391059,
        0.25120519, -0.30277595,  0.55549308,  0.532363  , -0.94326266,
       -0.11531473, -0.28370833, -0.02571836, -0.04334033,  0.82199106,
       -0.34950335,  0.76751985, -0.55187205,  0.0438944 ,  0.06823032,
        0.02053484, -0.55512943,  0.26875852, -0.343946  , -0.66814009,
        0.2792386 ,  0.05839992, -0.41565508,  0.22119522,  0.75239775,
       -0.34765832,  0.48652815, -0.14959935, -0.42217728, -0.69020268,
       -0.08470223, -0.36639052,  0.79802137,  0.49673195,  0.0364399 ,
        0.63688053, -0.53358692, -0.15931395,  0.34396112, -0.11031759,
       -0.6940359 ,  0.94680489,  0.30427494, -0.54026504,  0.1558066 ,
        0.19759366, -0.95170309, -0.66806906, -0.04757413,  0.26429521,
        0.41225482,  0.40186121, -0.1113431 , -0.35732416,  0.11043387,
        0.32699142,  0.46134402,  0.50338009,  0.88920733, -0.11650413,
       -0.15962027, -0.58777586, -0.27285518, -0.50946373, -0.14773305,
       -0.11379681,  0.55571533,  0.0873746 , -0.35599632, -0.49388313,
        0.14297583, -0.1704761 , -0.49123941,  0.89220858,  0.26666767,
       -0.82413835,  0.12283171,  0.35517504, -0.44511498, -0.03835261,
        0.40741921, -0.55277576,  0.04296405,  0.15117203,  0.21359713,
       -0.09945952,  0.17575688,  0.17078213, -0.47662051,  0.39528833])

In [5]:
# Test Alphien Lib
from alphien import data

Hello Surya, welcome to Alphien!

Importing your Alphien sub-packages...

import alphien.community
import alphien.data
import alphien.python
import alphien.wiki

Importing your Qlib functions...                                   from team:

import alphien.another_attempt                                     # TeamAlphien
import alphien.another_other_attempt                               # TeamAlphien
import alphien.smaCross                                            # TeamAlphien
import alphien.importTestPrivate                                   # TeamAlphien
import alphien.secondFunction                                      # TeamAlphien
import alphien.hellohello                                          # TeamRiyan
import alphien.hellosub                                            # TeamRiyan

Alphien environment imported. Let's do some research now!

In [8]:
data.getHistoryData("USDAUD Curncy", las)

            close_price
date
1971-01-05       0.8987
1971-01-06       0.8983
1971-01-07       0.8977
1971-01-08       0.8978
1971-01-11       0.8990
...                 ...
2020-07-10       1.4381
2020-07-13       1.4342
2020-07-14       1.4378
2020-07-15       1.4254
2020-07-16       1.4296

[12635 rows x 1 columns]

In [7]:
data.getHistoryData("GCH20 Comdty", )

            close_price
date
2019-12-30       1521.6
2019-12-31       1526.5
2020-01-02       1531.4
2020-01-03       1555.5
2020-01-06       1572.0
2020-01-07       1577.6
2020-01-08       1563.8
2020-01-09       1557.8
2020-01-10       1563.6
2020-01-13       1553.7
2020-01-14       1548.0
2020-01-15       1557.2
2020-01-16       1553.7
2020-01-17       1563.6
2020-01-20       1564.0
2020-01-21       1560.8
2020-01-22       1560.0
2020-01-23       1568.8
2020-01-24       1575.2
2020-01-27       1580.6
2020-01-28       1572.8
2020-01-29       1573.5
2020-01-30       1586.5
2020-01-31       1584.9
2020-02-03       1579.5
2020-02-04       1552.7
2020-02-05       1560.1
2020-02-06       1567.2
2020-02-07       1570.6
2020-02-10       1576.6
2020-02-11       1567.2
2020-02-12       1568.8
2020-02-13       1576.3
2020-02-14       1583.8
2020-02-17       1583.5
2020-02-18       1601.0
2020-02-19       1608.8
2020-02-20       1617.4
2020-02-21       1645.1
2020-02-24       1673.5
2020-02-25       1647.0
2020-02-26       1640.4
2020-02-27       1640.0
2020-02-28       1564.1